// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwi1nMeNejVpez2FvK3mQy7Q7ereqj5-s',
    appId: '1:1063419008348:web:d5e434a5af2da9631d5d99',
    messagingSenderId: '1063419008348',
    projectId: 'teacher-task-app',
    authDomain: 'teacher-task-app.firebaseapp.com',
    databaseURL: 'https://teacher-task-app-default-rtdb.firebaseio.com',
    storageBucket: 'teacher-task-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcBsWjOYWPJ9BjLo15WvDa8Eoc0fR76eE',
    appId: '1:1063419008348:android:41d2bd09a8208d531d5d99',
    messagingSenderId: '1063419008348',
    projectId: 'teacher-task-app',
    databaseURL: 'https://teacher-task-app-default-rtdb.firebaseio.com',
    storageBucket: 'teacher-task-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzDDxLOrjI6MyzyDgQ9xjqC3Z8Qn7FrOM',
    appId: '1:1063419008348:ios:659fb8025dcbba2c1d5d99',
    messagingSenderId: '1063419008348',
    projectId: 'teacher-task-app',
    databaseURL: 'https://teacher-task-app-default-rtdb.firebaseio.com',
    storageBucket: 'teacher-task-app.firebasestorage.app',
    iosBundleId: 'com.example.teacherGradingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzDDxLOrjI6MyzyDgQ9xjqC3Z8Qn7FrOM',
    appId: '1:1063419008348:ios:659fb8025dcbba2c1d5d99',
    messagingSenderId: '1063419008348',
    projectId: 'teacher-task-app',
    databaseURL: 'https://teacher-task-app-default-rtdb.firebaseio.com',
    storageBucket: 'teacher-task-app.firebasestorage.app',
    iosBundleId: 'com.example.teacherGradingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwi1nMeNejVpez2FvK3mQy7Q7ereqj5-s',
    appId: '1:1063419008348:web:a0168fc981b12a371d5d99',
    messagingSenderId: '1063419008348',
    projectId: 'teacher-task-app',
    authDomain: 'teacher-task-app.firebaseapp.com',
    databaseURL: 'https://teacher-task-app-default-rtdb.firebaseio.com',
    storageBucket: 'teacher-task-app.firebasestorage.app',
  );
}
